language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0
env:
  global:
    - secure: "Pi0WhqSukli7SEJZ2JeodiDljC0psriSLLlp8TceBas4COTiPUZZ3JNsVAJSzkqf6+bLMREUIGvoOckIsC0aff2p/XgPJb+JoppN+VpQFA0roqc80FDWeMNUhAq/nWUOAtPDhxPZNMmBUhZNCeIJy7eahmxPemCSBfrH0PovaH6mSYLoMRmxmZiWqsOGMXds4/2nna6/41JMlWPGiXL3XwEItuFt6z8GYxN8yEkxI2yYFml3pX5Tn0PizpakPoJoAOoLgJBcNZBMexyE8rSAfy2K3Os30maLsuqc/UvK+HefcTLY1Nqyl4hlz3FX1WJH0pXZkiiDCG9M6Q94kdze+imy7SZnsP20XtNpYqzbiAd7Xafp1dXC/177oZH5dLq8vPwyiAN0kEJouba1OU5KKMUC3nqu3Fk1QdFOw3VLcnadhU9hi7vIXsTUnAmg9oYT7N6938NSj4/A+NSRizgko95eHVrKw9aliItYbOnGv6XCZteHQ1VcTIzN93vFJlA/ns7cs4W9o9bEE65VJ4mrp4YOhCQ3L4EbvB2YM8GMO1FXqEXJq6/U0pBMMW9+A0DQ5SgkAlwPqQ3D+hdmpIkrLeRZ6NpszUfrPAzhqN3sr5lCr7HNurYk6zNTMVo2d+O8CktL1JuLBEis4KW2doc5huh/BYy+js2NA8s1BdtCDSA="
    - MIX_ENV=test

script: mix coveralls.travis
